config/routes.rb
#Tv::Engine.routes.draw do
Rails.application.routes.draw do
  scope :module => 'gluttonberg' do
    scope :module => 'tv' do
      namespace :admin do
        scope :module => 'settings' do
          resources :video_settings do
            get 'delete', :on => :member
          end
        end
      end
    end
  end
end

app/models/gluttonberg/tv/video_setting.rb
module Gluttonberg
  module Tv
    class VideoSetting < ActiveRecord::Base
      self.table_name = "tv_video_settings"
      attr_accessible :name, :file_postfix, :command

      #initialize with default video settings
      def self.init
        self.create(:name => "High MP4", :file_postfix => "high.mp4" , :command => "ffmpeg -i $file$ -vb 1500k -vcodec libx264 -g 30 -y")
        self.create(:name => "High WEBM", :file_postfix => "high.webm" , :command => "ffmpeg -i $file$ -vb 1500k -vcodec libvpx -acodec libvorbis -ab 160000 -f webm -g 30 -y")
        self.create(:name => "High OGV", :file_postfix => "high.ogv" , :command => "ffmpeg -i $file$ -vb 1500k -vcodec libtheora -acodec libvorbis -ab 160000 -g 30 -y")
        self.create(:name => "Medium MP4", :file_postfix => "medium.mp4" , :command => "ffmpeg -i $file$ -vb 600k -vcodec libx264 -g 30 -y")
        self.create(:name => "Medium WEBM", :file_postfix => "medium.webm" , :command => "ffmpeg -i $file$ -vb 600k -vcodec libvpx -acodec libvorbis -ab 160000 -f webm -g 30 -y")
        self.create(:name => "Medium OGV", :file_postfix => "medium.ogv" , :command => "ffmpeg -i $file$ -vb 600k -vcodec libtheora -acodec libvorbis -ab 160000 -g 30 -y")
        self.create(:name => "Low MP4", :file_postfix => "low.mp4" , :command => "ffmpeg -i $file$ -vb 300k -vcodec libx264 -g 30 -y")
        self.create(:name => "Low OGV", :file_postfix => "low.ogv" , :command => "ffmpeg -i $file$ -vb 300k -vcodec libtheora -acodec libvorbis -ab 160000 -g 30 -y")
        self.create(:name => "Low WEBM", :file_postfix => "low.webm" , :command => "ffmpeg -i $file$ -vb 300k -vcodec libvpx -acodec libvorbis -ab 160000 -f webm -g 30 -y")
      end

    end
  end
end#Gluttonberg

app/models/tv/video_setting.rb
module Tv
  class VideoSetting < ActiveRecord::Base
    self.table_name = "tv_video_settings"
    attr_accessible :name, :file_postfix, :command

    #initialize with default video settings
    def self.init
      self.create(:name => "High MP4", :file_postfix => "high.mp4" , :command => "ffmpeg -i $file$ -vb 1500k -vcodec libx264 -g 30 -y")
      self.create(:name => "High WEBM", :file_postfix => "high.webm" , :command => "ffmpeg -i $file$ -vb 1500k -vcodec libvpx -acodec libvorbis -ab 160000 -f webm -g 30 -y")
      self.create(:name => "High OGV", :file_postfix => "high.ogv" , :command => "ffmpeg -i $file$ -vb 1500k -vcodec libtheora -acodec libvorbis -ab 160000 -g 30 -y")
      self.create(:name => "Medium MP4", :file_postfix => "medium.mp4" , :command => "ffmpeg -i $file$ -vb 600k -vcodec libx264 -g 30 -y")
      self.create(:name => "Medium WEBM", :file_postfix => "medium.webm" , :command => "ffmpeg -i $file$ -vb 600k -vcodec libvpx -acodec libvorbis -ab 160000 -f webm -g 30 -y")
      self.create(:name => "Medium OGV", :file_postfix => "medium.ogv" , :command => "ffmpeg -i $file$ -vb 600k -vcodec libtheora -acodec libvorbis -ab 160000 -g 30 -y")
      self.create(:name => "Low MP4", :file_postfix => "low.mp4" , :command => "ffmpeg -i $file$ -vb 300k -vcodec libx264 -g 30 -y")
      self.create(:name => "Low OGV", :file_postfix => "low.ogv" , :command => "ffmpeg -i $file$ -vb 300k -vcodec libtheora -acodec libvorbis -ab 160000 -g 30 -y")
      self.create(:name => "Low WEBM", :file_postfix => "low.webm" , :command => "ffmpeg -i $file$ -vb 300k -vcodec libvpx -acodec libvorbis -ab 160000 -f webm -g 30 -y")
    end

  end
end

app/controllers/gluttonberg/tv/admin/settings/video_settings_controller.rb
# encoding: utf-8

module Gluttonberg
  module Tv
    module Admin
      module Settings
        class VideoSettingsController < Gluttonberg::Admin::BaseController
          before_filter :find_setting, :only => [:delete, :edit, :update, :destroy]
          before_filter :authorize_user
          record_history :@video_setting

          def index
            @video_settings = VideoSetting.all
          end

          def new
            @video_setting   = VideoSetting.new
          end

          def edit
          end

          def delete
            display_delete_confirmation(
              :title      => "Delete “#{@video_setting.name}” video setting?",
              :url        => admin_video_setting_path(@video_setting),
              :return_url => admin_video_settings_path ,
              :warning    => ""
            )
          end

          def create
            @video_setting = VideoSetting.new(params["gluttonberg_tv_video_setting"])
            if @video_setting.save
              flash[:notice] = "The video setting was successfully created."
              redirect_to admin_video_settings_path
            else
              render :new
            end
          end

          def update
            if @video_setting.update_attributes(params["gluttonberg_tv_video_setting"]) || !@video_setting.dirty?
              flash[:notice] = "The video setting was successfully updated."
              redirect_to admin_video_settings_path
            else
              flash[:error] = "Sorry, The video setting could not be updated."
              render :edit
            end
          end

          def destroy
            if @video_setting.destroy
              flash[:notice] = "The video setting was successfully deleted."
              redirect_to admin_video_settings_path
            else
              flash[:error] = "There was an error deleting the video setting."
              redirect_to admin_video_settings_path
            end
          end

          private

            def find_setting
              @video_setting = VideoSetting.find(params[:id])
              raise ActiveRecord::RecordNotFound unless @video_setting
              authorize! :manage_object, @video_setting
            end

            def authorize_user
              authorize! :manage, Gluttonberg::Tv::VideoSetting
            end

        end
      end
    end
  end #Tv
end #Gluttonberg

app/controllers/gluttonberg/tv/application_controller.rb
module Gluttonberg
  module Tv
    class ApplicationController < ActionController::Base
    end
  end
end

app/helpers/gluttonberg/tv/application_helper.rb
module Gluttonberg
  module Tv
    module ApplicationHelper
    end
  end
end

app/views/gluttonberg/tv/admin/settings/video_settings/_form.html.haml
= form_for(@video_setting, :url => url , :html => {:class => "validation"}) do  |f|
  = gb_error_messages_for(@video_setting)
  .span5
    %legend
      Video Setting
    %p
      = f.label :name
      = f.text_field(:name)
    %p
      = f.label :file_postfix
      = f.text_field(:file_postfix)
    %p
      = f.label :command
      = f.text_area(:command   )

    = form_controls(admin_video_settings_path)

  .clear

app/views/gluttonberg/tv/admin/settings/video_settings/edit.html.haml
- @window_title = "Video Settings"
- @page_title = "#{link_to "Settings", admin_configurations_path} > #{link_to('Video Settings', admin_video_settings_path)} > Edit video setting"

= render :partial => "form" , :locals => { :url => admin_video_setting_path( @video_setting) }

app/views/gluttonberg/tv/admin/settings/video_settings/index.html.haml
- @window_title = "Video Settings"
- @page_title = "#{link_to "Settings", admin_configurations_path} > Video Settings"
.row-fluid
  = render :partial => "/gluttonberg/admin/settings/main/sidebar"
  .span9
    .row-fluid
      .page-header
        %h1
          = @page_title.html_safe
      .subnav
        = sub_nav do
          = nav_link('New', new_admin_video_setting_path)

      - if @video_settings.empty?
        %p.empty No video settings
      - else
        %table{:cellspacing => 0, :cellpadding => 0, :summary => "List of video settings", :class => "table table-bordered"}
          %thead
            %tr
              %th Name
              %th Postfix
              %th Command
              %th.controls Controls
          %tbody
            - i = 0
            - for video_setting in @video_settings
              - i += 1
              %tr{ :class => "#{i % 2 == 0? "even" : ""}"}
                %td= video_setting.name
                %td= video_setting.file_postfix
                %td= video_setting.command
                %td.controls
                  = link_to('Edit', edit_admin_video_setting_path(video_setting), :class => "btn")
                  = link_to "Delete", delete_admin_video_setting_path(video_setting), :class => "btn btn-danger"

app/views/gluttonberg/tv/admin/settings/video_settings/new.html.haml
- @window_title = "Video Settings"
- @page_title = "#{link_to "Settings", admin_configurations_path} > #{link_to('Video Settings', admin_video_settings_path)} > Add a new video setting"

= render :partial => "form", :locals => { :url => admin_video_settings_path }